### ISSUE TITLE
Loose Envify should be dev dependency?

### ISSUE THREAD

**Issue by buffet-time** [silverspectro/vue-clickaway2#4]
Am i wrong to assume that Loose Envify should be moved to dev dependency? Because from what i see it's only being used in build.js which isn't really necessary for the package when someones going to import it and use it as is. If they end up needing to change something and rebuild they'd need to go into dev anyways.

Unsure of your thoughts on this or if i'm mistaken but thought I might bring it up if we can make the package require 0 dependencies.

**Comment by silverspectro** [comment]
I didn't really thought about the build flow or anything.
To let you know, I just forked the project to maintain it and respond to the PR (plus making my own changes) mainly because the original author wasn't responding anymore.
But I think it would be a good thing to have 0 dependencies of course! And it is possible and easy.
Feel free man, I don't have the time to do it, so you are the boss and I'll review for the meantime if it is okay for you.

**Comment by buffet-time** [comment]
I'll look into it, in the meantime could you add me to contributor on the node site so i can update the package after a merge is completed or the like as needed? https://www.npmjs.com/~daniel_turcich

**Comment by buffet-time** [comment]
Could you please update the package with the latest merge?

**Comment by silverspectro** [comment]
done -> 2.3.1 on npm

**Comment by buffet-time** [comment]
Can't be bothered atm to look into this so i'll close it. Might look at this later.
